worker_processes 1;
pid /var/run/nginx.pid;
error_log /proc/1/fd/2 info;

events {
    worker_connections 1024;
}

http {
    access_log /proc/1/fd/1 combined;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 8095 default_server;

        location / {
            # Using a variable for the URL helps Nginx handle the query string merge
            set $backend "http://${SERVER_HOST}:${SERVER_PORT}";
            
            # This appends the token and preserves existing arguments ($args)
            proxy_pass $backend$uri?code=${MA_TOKEN}&$args;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Support for WebSockets
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_http_version 1.1;
        }
    }
}
